// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.NetworkTask.CountDots.GetClasses~System.Collections.Generic.List{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Qualia.Controls.OutputNeuronControl.OrdinalNumberChanged(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.NetworkTask.MNIST.GetClasses~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Usage", "CA2211:Non-constant fields should not be visible", Justification = "<Pending>", Scope = "member", Target = "~F:Tools.RenderTime.Network")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.ActivationFunctionList.None")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.ActivationFunctionList.LogisticSigmoid")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.ActivationFunctionList.SymmetricSigmoid")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.ActivationFunctionList.Softsign")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.ActivationFunctionList.Tanh")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.ActivationFunctionList.ReLu")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.ActivationFunctionList.StepConst")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~F:Qualia.Controls.ErrorMatrix.Matrix")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:Qualia.Controls.ErrorMatrix.#ctor(System.Collections.Generic.List{System.String})")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.LogisticSigmoid._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.LogisticSigmoid._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.None._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.None._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.ReLu._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.ReLu._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.Softsign._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.Softsign._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.StepConst._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.StepConst._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.SymmetricSigmoid._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.SymmetricSigmoid._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.Tanh._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.Tanh._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.CostFunctionList.MSE._derivative(Qualia.NetworkDataModel,Qualia.NeuronDataModel)~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.CostFunctionList.MSE._do(Qualia.NetworkDataModel)~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.LogisticSigmoid._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.LogisticSigmoid._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.ReLu._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.ReLu._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.Softsign._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.Softsign._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.StepConst._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.StepConst._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.SymmetricSigmoid._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.SymmetricSigmoid._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.Tanh._derivative(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.ActivationFunctionList.Tanh._do(System.Double,System.Nullable{System.Double})~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.CostFunctionList.MSE._derivative(Qualia.NetworkDataModel,Qualia.NeuronDataModel)~System.Double")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Tools.CostFunctionList.MSE._do(Qualia.NetworkDataModel)~System.Double")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.CostFunctionList.Helper")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.CostFunctionList.MSE")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.DynamicStatistics.PlotPoint")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.DynamicStatistics.PlotPoints")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.NetworkTask.CountDots")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.NetworkTask.Helper")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.NetworkTask.MNIST")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.NetworkTaskResult.Helper")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Tools.RandomizeMode.Helper")]
